<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-11-11 12:10

$extensionPath = t3lib_extMgm::extPath('pagewizard');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_pagewizard_controller_pagewizardcontroller' => $extensionClassesPath . 'Controller/PageWizardController.php',
	'tx_pagewizard_domain_model_page' => $extensionClassesPath . 'Domain/Model/Page.php',
	'tx_pagewizard_domain_repository_pagerepository' => $extensionClassesPath . 'Domain/Repository/PageRepository.php',
	'tx_pagewizard_viewhelpers_format_rawviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/RawViewHelper.php',
);
?>